### ISSUE TITLE
优化自动排包的配置方式

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#117]
migrate from https://github.com/sofastack/sofa-serverless/issues/330

同时避免，在多bundle 里配置的时候目录存放与配置解析的地址不一致导致的问题
![image](https://github.com/koupleless/koupleless/assets/3754074/66f4724a-2a25-4b76-929a-916376d245f0)

![image](https://github.com/koupleless/koupleless/assets/3754074/09fd72fc-fa89-4970-a37a-4a661a2a5571)

**Comment by gaosaroma** [comment]
优化后的配置方式：
1. 读取主目录下的 conf/ark/application.properties 或 conf/ark/application.yml
2. 无需配置 `packExcludesConfig`

application.properties 的配置方式：

```
# excludes 中配置 ${groupId}:{artifactId}, 不同依赖以逗号隔开
com.alipay.sofa.ark.module.dependency.excludes=org.apache.commons:commons-lang3,commons-beanutils:commons-beanutils
# excludeGroupIds 中配置 ${groupId}, 不同依赖以逗号隔开
com.alipay.sofa.ark.module.dependency.excludeGroupIds=org.springframework
# excludeArtifactIds 中配置 ${artifactId}, 不同依赖以逗号隔开
com.alipay.sofa.ark.module.dependency.excludeArtifactIds=sofa-ark-spi
```


```
# excludes 中配置 ${groupId}:{artifactId}, 不同依赖以逗号隔开
# excludeGroupIds 中配置 ${groupId}, 不同依赖以逗号隔开
# excludeArtifactIds 中配置 ${artifactId}, 不同依赖以逗号隔开
com:
  alipay:
    sofa:
      ark:
        module:
          dependency:
            excludes:
              - org.apache.commons:commons-lang3
              - commons-beanutils:commons-beanutils
            excludeGroupIds:
              - org.springframework
            excludeArtifactIds:
              - sofa-ark-spi
```
